"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";
import { Project, GenerationResponse, UnifiedBlueprint } from "@/lib/types";
import {
  Sparkles,
  Layers,
  Search,
  Cpu,
  Palette,
  TrendingUp,
  ShieldAlert,
  Download,
  Printer,
  CheckCircle2,
  ExternalLink,
  Target,
  FileCode,
  ShieldCheck,
  AlertTriangle
} from "lucide-react";

export default function BlueprintViewerPage() {
  const params = useParams();
  const projectId = params.id as string;

  const [project, setProject] = useState<Project | null>(null);
  const [generation, setGeneration] = useState<GenerationResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<string>("executive");

  useEffect(() => {
    loadBlueprint();
  }, [projectId]);

  const loadBlueprint = async () => {
    try {
      setLoading(true);
      const [proj, gen] = await Promise.all([
        api.getProject(projectId),
        api.getLatestGeneration(projectId),
      ]);
      setProject(proj);
      setGeneration(gen);
    } catch (err: any) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportMarkdown = () => {
    if (!generation?.blueprint) return;
    const content = JSON.stringify(generation.blueprint, null, 2);
    const blob = new Blob([content], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project?.name || "startup"}-blueprint.json`;
    a.click();
  };

  if (loading) {
    return (
      <div className="max-w-6xl mx-auto px-4 py-16 text-center">
        <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-500 mb-4" />
        <p className="text-sm text-zinc-400 font-mono">Assembling Unified Startup Blueprint...</p>
      </div>
    );
  }

  const bp: UnifiedBlueprint = generation?.blueprint || {};
  const market = bp.market_analysis;
  const product = bp.product_strategy;
  const tech = bp.technical_architecture;
  const ux = bp.ux_strategy;
  const business = bp.business_strategy;
  const strategy = bp.strategy_assessment;

  const tabs = [
    { id: "executive", name: "Executive Summary & Scores", icon: Sparkles },
    { id: "market", name: "Market & Competitors", icon: Search },
    { id: "product", name: "Product & MVP", icon: Layers },
    { id: "tech", name: "Technical Architecture", icon: Cpu },
    { id: "ux", name: "UI/UX & Flows", icon: Palette },
    { id: "business", name: "Business & Pricing", icon: TrendingUp },
    { id: "contradictions", name: "Risks & Cross-Checks", icon: ShieldAlert },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 mb-8 border-b border-zinc-800">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold text-indigo-400 uppercase tracking-wider mb-1">
            <Sparkles className="w-3.5 h-3.5" />
            StartupForge AI Unified Blueprint
          </div>
          <h1 className="text-3xl font-extrabold text-white tracking-tight">{project?.name}</h1>
          <p className="text-xs text-zinc-400 mt-1">Generated by 6 Coordinated LangGraph Agents</p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleExportMarkdown}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-200 transition"
          >
            <Download className="w-4 h-4" /> Export JSON
          </button>
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white transition shadow-md"
          >
            <Printer className="w-4 h-4" /> Print Report
          </button>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="flex items-center gap-2 overflow-x-auto pb-4 mb-8 border-b border-zinc-900 scrollbar-none">
        {tabs.map((t) => {
          const Icon = t.icon;
          const isActive = activeTab === t.id;
          return (
            <button
              key={t.id}
              onClick={() => setActiveTab(t.id)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold whitespace-nowrap transition ${
                isActive
                  ? "bg-indigo-600 text-white shadow-lg shadow-indigo-600/20"
                  : "bg-zinc-900/60 text-zinc-400 hover:text-white hover:bg-zinc-800"
              }`}
            >
              <Icon className="w-4 h-4" />
              {t.name}
            </button>
          );
        })}
      </div>

      {/* Tab Content */}
      <div className="space-y-8">
        {/* 1. Executive Summary Tab */}
        {activeTab === "executive" && (
          <div className="space-y-8">
            {/* Health Scores */}
            {strategy?.domain_scores && (
              <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
                {strategy.domain_scores.map((sc, i) => (
                  <div key={i} className="p-4 rounded-xl glass-panel text-center">
                    <p className="text-xs font-semibold text-zinc-400 uppercase">{sc.domain}</p>
                    <p className="text-3xl font-extrabold text-indigo-400 mt-1 mb-1">{sc.score} / 10</p>
                    <p className="text-[11px] text-zinc-500">{sc.rationale}</p>
                  </div>
                ))}
              </div>
            )}

            {/* Strategic Overview */}
            <div className="p-6 rounded-2xl glass-panel">
              <h3 className="text-lg font-bold text-white mb-3">Executive Summary</h3>
              <p className="text-sm text-zinc-300 leading-relaxed whitespace-pre-wrap">
                {strategy?.executive_summary || "Comprehensive startup plan synthesized across all 6 specialized domains."}
              </p>
            </div>

            {/* Key Next Steps */}
            {strategy?.next_steps && (
              <div className="p-6 rounded-2xl glass-card">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2">
                  <Target className="w-4 h-4 text-emerald-400" />
                  Recommended Actionable Next Steps
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {strategy.next_steps.map((st, i) => (
                    <div key={i} className="p-3.5 rounded-xl bg-zinc-900/80 border border-zinc-800 flex items-start gap-2.5">
                      <span className="w-5 h-5 rounded-full bg-emerald-500/20 text-emerald-400 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                        {i + 1}
                      </span>
                      <span className="text-xs text-zinc-300">{st}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* 2. Market Tab */}
        {activeTab === "market" && (
          <div className="space-y-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 rounded-2xl glass-panel">
                <h3 className="text-base font-bold text-white mb-2">Industry Overview</h3>
                <p className="text-sm text-zinc-300">{market?.industry_overview || "N/A"}</p>
                <div className="mt-4 pt-4 border-t border-zinc-800">
                  <span className="text-xs text-zinc-400 font-semibold">Estimated Market Size:</span>
                  <p className="text-sm font-bold text-indigo-300 mt-0.5">{market?.market_size || "N/A"}</p>
                </div>
              </div>

              <div className="p-6 rounded-2xl glass-panel">
                <h3 className="text-base font-bold text-white mb-2">Target Market</h3>
                <p className="text-sm text-zinc-300">{market?.target_market || "N/A"}</p>
              </div>
            </div>

            {/* Competitors Table */}
            {market?.competitors && market.competitors.length > 0 && (
              <div className="p-6 rounded-2xl glass-card">
                <h3 className="text-base font-bold text-white mb-4">Competitor Intelligence Matrix</h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead>
                      <tr className="border-b border-zinc-800 text-zinc-400">
                        <th className="pb-3 font-semibold">Competitor</th>
                        <th className="pb-3 font-semibold">Strengths</th>
                        <th className="pb-3 font-semibold">Weaknesses</th>
                        <th className="pb-3 font-semibold">Pricing Model</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-zinc-800/60">
                      {market.competitors.map((comp, i) => (
                        <tr key={i} className="text-zinc-300">
                          <td className="py-3 font-bold text-white">{comp.name}</td>
                          <td className="py-3 text-emerald-400">{comp.strengths?.join(", ")}</td>
                          <td className="py-3 text-rose-400">{comp.weaknesses?.join(", ")}</td>
                          <td className="py-3 text-zinc-400">{comp.pricing}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}

        {/* 3. Product Tab */}
        {activeTab === "product" && (
          <div className="space-y-8">
            <div className="p-6 rounded-2xl glass-panel">
              <h3 className="text-base font-bold text-white mb-2">MVP Scope & Value Proposition</h3>
              <p className="text-sm text-zinc-300 mb-4">{product?.value_proposition || "N/A"}</p>
              <div className="p-4 rounded-xl bg-indigo-950/20 border border-indigo-800/40">
                <span className="text-xs font-semibold text-indigo-300 uppercase">Core MVP Scope:</span>
                <p className="text-xs text-zinc-300 mt-1">{product?.mvp_scope || "N/A"}</p>
              </div>
            </div>

            {/* Features */}
            {product?.features && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {product.features.map((feat, i) => (
                  <div key={i} className="p-4 rounded-xl glass-card">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="text-sm font-bold text-white">{feat.name}</h4>
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-zinc-800 text-indigo-300 border border-zinc-700">
                        {feat.priority}
                      </span>
                    </div>
                    <p className="text-xs text-zinc-400">{feat.description}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* 4. Tech Tab */}
        {activeTab === "tech" && (
          <div className="space-y-8">
            <div className="p-6 rounded-2xl glass-panel">
              <h3 className="text-base font-bold text-white mb-2">System Architecture Overview</h3>
              <p className="text-sm text-zinc-300 leading-relaxed mb-4">{tech?.system_overview || "N/A"}</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4 border-t border-zinc-800 text-xs">
                <div>
                  <span className="text-zinc-500">Backend:</span>
                  <p className="font-semibold text-zinc-200 mt-0.5">{tech?.backend_architecture || "N/A"}</p>
                </div>
                <div>
                  <span className="text-zinc-500">Frontend:</span>
                  <p className="font-semibold text-zinc-200 mt-0.5">{tech?.frontend_architecture || "N/A"}</p>
                </div>
              </div>
            </div>

            {/* Database & Security */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 rounded-2xl glass-card">
                <h4 className="text-sm font-bold text-white mb-2">Database Design</h4>
                <p className="text-xs text-zinc-300 leading-relaxed">{tech?.database_design || "N/A"}</p>
              </div>
              <div className="p-6 rounded-2xl glass-card">
                <h4 className="text-sm font-bold text-white mb-2">Security & Auth</h4>
                <p className="text-xs text-zinc-300 leading-relaxed">{tech?.security_strategy || "N/A"}</p>
              </div>
            </div>
          </div>
        )}

        {/* 5. UX Tab */}
        {activeTab === "ux" && (
          <div className="space-y-8">
            <div className="p-6 rounded-2xl glass-panel">
              <h3 className="text-base font-bold text-white mb-2">Information Architecture & Sitemap</h3>
              <p className="text-sm text-zinc-300 mb-4">{ux?.information_architecture || "N/A"}</p>
              {ux?.sitemap && (
                <div className="flex flex-wrap gap-2">
                  {ux.sitemap.map((page, i) => (
                    <span key={i} className="px-3 py-1 rounded-lg bg-zinc-900 border border-zinc-800 text-xs text-indigo-300 font-mono">
                      {page}
                    </span>
                  ))}
                </div>
              )}
            </div>

            {/* Screens */}
            {ux?.screens && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {ux.screens.map((scr, i) => (
                  <div key={i} className="p-4 rounded-xl glass-card">
                    <h4 className="text-sm font-bold text-white mb-1">{scr.name}</h4>
                    <p className="text-xs text-zinc-400 mb-3">{scr.purpose}</p>
                    <div className="text-[11px] text-zinc-500">
                      <span className="font-semibold text-zinc-400">Elements:</span> {scr.key_elements?.join(", ")}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* 6. Business Tab */}
        {activeTab === "business" && (
          <div className="space-y-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 rounded-2xl glass-panel">
                <h3 className="text-base font-bold text-white mb-2">Business & Revenue Model</h3>
                <p className="text-sm text-zinc-300">{business?.revenue_model || "N/A"}</p>
              </div>
              <div className="p-6 rounded-2xl glass-panel">
                <h3 className="text-base font-bold text-white mb-2">Go-to-Market Strategy</h3>
                <p className="text-sm text-zinc-300">{business?.gtm_strategy || "N/A"}</p>
              </div>
            </div>

            {/* Pricing Tiers */}
            {business?.pricing_tiers && (
              <div className="p-6 rounded-2xl glass-card">
                <h3 className="text-base font-bold text-white mb-4">Pricing Strategy</h3>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  {business.pricing_tiers.map((tier, i) => (
                    <div key={i} className="p-4 rounded-xl bg-zinc-900/80 border border-zinc-800">
                      <h4 className="text-sm font-bold text-indigo-400">{tier.name || `Tier ${i+1}`}</h4>
                      <p className="text-xl font-extrabold text-white mt-1 mb-2">{tier.price || "$0"}</p>
                      <p className="text-xs text-zinc-400">{tier.features || tier.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* 7. Contradictions & Risks Tab */}
        {activeTab === "contradictions" && (
          <div className="space-y-8">
            {/* Contradictions Flagged */}
            <div className="p-6 rounded-2xl glass-panel border border-amber-500/30 bg-amber-950/10">
              <h3 className="text-base font-bold text-amber-300 mb-2 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-amber-400" />
                Cross-Domain Strategic Contradictions Detected
              </h3>
              <p className="text-xs text-zinc-400 mb-4">
                The Chief Strategy Agent analyzed all domain outputs to prevent real-world startup failure modes.
              </p>

              {strategy?.contradictions && strategy.contradictions.length > 0 ? (
                <div className="space-y-3">
                  {strategy.contradictions.map((ct, i) => (
                    <div key={i} className="p-4 rounded-xl bg-zinc-900/90 border border-zinc-800">
                      <div className="flex items-center justify-between text-xs mb-1">
                        <span className="font-bold text-amber-400 uppercase">
                          {ct.domain_a} vs {ct.domain_b}
                        </span>
                        <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-rose-500/20 text-rose-300">
                          {ct.severity} severity
                        </span>
                      </div>
                      <p className="text-xs text-zinc-300 mt-1">
                        <span className="text-zinc-500">{ct.domain_a}:</span> {ct.finding_a}
                      </p>
                      <p className="text-xs text-zinc-300">
                        <span className="text-zinc-500">{ct.domain_b}:</span> {ct.finding_b}
                      </p>
                      <p className="text-xs text-emerald-400 font-medium mt-2 pt-2 border-t border-zinc-800/60">
                        Recommendation: {ct.recommendation}
                      </p>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-emerald-400">No major cross-agent contradictions detected.</p>
              )}
            </div>

            {/* Critical Risks */}
            {strategy?.critical_risks && (
              <div className="p-6 rounded-2xl glass-card">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-4">
                  Critical Venture Risks
                </h3>
                <ul className="space-y-2 text-xs text-zinc-300 list-disc list-inside">
                  {strategy.critical_risks.map((rk, i) => (
                    <li key={i} className="leading-relaxed">{rk}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}